name: stuf-sync

on:
  push:
    tags:
      - "production-*.*.*"
      - "sync-*.*.*"

jobs:
  build-and-deploy:
    runs-on: docker
    uses: asbjornenge/forgejo-ci/.forgejo/workflows/stuf-sync.yml@main
    secrets: inherit
